const mongoose = require("mongoose");

/*
==========================================
Question Part Schema (For Split Questions)
==========================================
Example:
14 Marks
a) 10 Marks
b) 4 Marks
*/

const questionPartSchema = new mongoose.Schema({
  label: {
    type: String,
  },

  marks: {
    type: Number,
  },

  questionText: {
    type: String,
  },

  // Ideal answer generated by Gemini
  modelAnswer: {
    type: String,
    default: "",
  },

  // Important points expected in the answer
  markingScheme: {
    keyPoints: {
      type: [String],
      default: [],
    },
  },
});

/*
==========================================
Question Schema
==========================================
Supports:
- MCQ
- True / False
- Fill in the Blank
- 2 Marks
- 5 Marks
- Split Questions
*/

const questionSchema = new mongoose.Schema({
  questionText: {
    type: String,
  },

  marks: {
    type: Number,
    required: true,
  },

  topic: {
    type: String,
    required: true,
  },

  questionType: {
    type: String,
    default: "",
  },

  // Used only for MCQs
  options: [
    {
      type: String,
    },
  ],

  /*
  ==========================================
  Objective Question Evaluation
  ==========================================
  */

  // MCQ / True False / Fill Blank
  correctAnswer: {
    type: String,
    default: "",
  },

  /*
  ==========================================
  Descriptive Question Evaluation
  ==========================================
  */

  // Faculty quality ideal answer
  modelAnswer: {
    type: String,
    default: "",
  },

  // Important points expected in answer
  markingScheme: {
    keyPoints: {
      type: [String],
      default: [],
    },
  },

  /*
  ==========================================
  Split Questions
  ==========================================
  */

  parts: [questionPartSchema],
});

/*
==========================================
Blueprint Schema
==========================================
*/

const blueprintItemSchema = new mongoose.Schema({
  marks: {
    type: Number,
    required: true,
  },

  count: {
    type: Number,
    required: true,
  },

  pattern: {
    type: [Number],
    default: [],
  },
});

/*
==========================================
Paper Schema
==========================================
*/

const paperSchema = new mongoose.Schema(
  {
    syllabusId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Syllabus",
      required: true,
    },

    subject: {
      type: String,
      required: true,
    },

    blueprint: [blueprintItemSchema],

    questions: [questionSchema],
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Paper", paperSchema);